create table irregularity
(
    id                      VARCHAR(8) PRIMARY KEY,
    title                   VARCHAR(255),
    description             TEXT,
    date                    TIMESTAMP    NOT NULL,
    locked                  BOOLEAN      NOT NULL,
    student_id              VARCHAR(255),
    professor_id            VARCHAR(255),
    room_name               VARCHAR(255),
    subject_id              VARCHAR(255),
    administrative_staff_id VARCHAR(255),
    general_irregularity    VARCHAR(255),
    type                    VARCHAR(255) NOT NULL,
    status                  VARCHAR(255) NOT NULL,
    user_id                 VARCHAR(255),
    marked_by               VARCHAR(255),
    marked_on               TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES student (student_index),
    FOREIGN KEY (professor_id) REFERENCES professor (id),
    FOREIGN KEY (room_name) REFERENCES room (name),
    FOREIGN KEY (subject_id) REFERENCES subject (id),
    FOREIGN KEY (administrative_staff_id) REFERENCES auth_user (id),
    FOREIGN KEY (user_id) REFERENCES auth_user (id)
);

create table irregularity_comment
(
    id              bigint generated by default as identity not null,
    comment         TEXT,
    date_answered   TIMESTAMP,
    staff_user_id   VARCHAR(255),
    irregularity_id VARCHAR(8) not null,
    FOREIGN KEY (staff_user_id) REFERENCES auth_user (id),
    FOREIGN KEY (irregularity_id) REFERENCES irregularity (id) ON DELETE CASCADE
);
