DROP TABLE IF EXISTS topic_commission_member cascade;
DROP TABLE IF EXISTS topic_file cascade;
DROP TABLE IF EXISTS comment cascade;
DROP TABLE IF EXISTS topic_comment cascade;
DROP TABLE IF EXISTS commission_member cascade;
DROP TABLE IF EXISTS topic_commission_members cascade;
DROP TABLE IF EXISTS topic cascade;
drop table if exists teaching_and_scientific_meeting cascade;

CREATE TABLE commission_member
(
    id           bigint generated by default as identity not null primary key,
    professor_id varchar(255),
    type         VARCHAR(255)
);

CREATE TABLE topic_file
(
    id        bigint generated by default as identity not null primary key,
    file_name VARCHAR(255),
    content   bytea
);

CREATE TABLE topic
(
    id                        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    serial_number             VARCHAR(255),
    category             VARCHAR(255),
    status             VARCHAR(255),
    sub_category_name         VARCHAR(255),
    description               VARCHAR(6000),
    is_accepted               BOOLEAN,
    accept_number             INTEGER,
    against_number            INTEGER,
    sustained_number          INTEGER,
    discussion                VARCHAR(255),
    file_url                  VARCHAR(255),
    is_votable                BOOLEAN DEFAULT TRUE,
    requested_by_professor_id varchar(255),
    meeting_id                varchar(255),
    mentioned_student_id      VARCHAR(255),
    mentioned_professor_id    VARCHAR(255),
    file_id             BIGINT
);

CREATE TABLE topic_comment
(
    id           bigint generated by default as identity not null primary key,
    comment_text VARCHAR(4000),
    topic_id     BIGINT,
    date_posted  TIMESTAMP,
    professor_id varchar(255)
);

CREATE TABLE topic_commission_members
(
    topics_id             BIGINT,
    commission_members_id BIGINT,
    PRIMARY KEY (topics_id, commission_members_id)
);

CREATE TABLE teaching_and_scientific_meeting
(
    meeting_number varchar(255) PRIMARY KEY,
    date   date,
    present_members INTEGER,
    eligible_members INTEGER,
    room_name varchar(255),
    chair_man_id varchar(255)
);

ALTER TABLE commission_member
    ADD FOREIGN KEY (professor_id) REFERENCES professor (id);

ALTER TABLE topic_comment
    ADD FOREIGN KEY (topic_id) REFERENCES topic (id),
    ADD FOREIGN KEY (professor_id) REFERENCES professor (id);

ALTER TABLE topic
    ADD FOREIGN KEY (requested_by_professor_id) REFERENCES professor (id),
    ADD FOREIGN KEY (meeting_id) REFERENCES teaching_and_scientific_meeting (meeting_number),
    ADD FOREIGN KEY (mentioned_student_id) REFERENCES student (student_index),
    ADD FOREIGN KEY (mentioned_professor_id) REFERENCES professor (id),
    ADD FOREIGN KEY (file_id) REFERENCES topic_file (id);

ALTER TABLE topic_commission_members
    ADD FOREIGN KEY (topics_id) REFERENCES topic (id),
    ADD FOREIGN KEY (commission_members_id) REFERENCES commission_member (id);

ALTER TABLE teaching_and_scientific_meeting
    ADD CONSTRAINT fk_room FOREIGN KEY (room_name) REFERENCES room(name);

ALTER TABLE teaching_and_scientific_meeting
    ADD CONSTRAINT fk_chairMan FOREIGN KEY (chair_man_id) REFERENCES auth_user(id);