create table if not exists item
(
    id            bigint generated by default as identity not null
    primary key,
    name            varchar(255),
    item_category   varchar(255),
    description TEXT,
    date_issue_created DATE,
    location varchar(255),
    item_type varchar(255),
    image bytea,
    handover boolean default false,
    user_id varchar(255),
    phone_number varchar(50),

    CONSTRAINT fk_item_user FOREIGN KEY (user_id)
    REFERENCES auth_user(id)
);

create table if not exists comment
(
    id            bigint generated by default as identity not null
    primary key,
    content TEXT,
    author_id varchar(255),
    item_id BIGINT,
    parent_comment_id BIGINT,
    date_time TIMESTAMP,
    image bytea,

    CONSTRAINT fk_comment_author FOREIGN KEY (author_id)
    REFERENCES auth_user(id)
    ON DELETE SET NULL,

    CONSTRAINT fk_comment_item FOREIGN KEY (item_id)
    REFERENCES item(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_comment_parent FOREIGN KEY (parent_comment_id)
    REFERENCES comment(id)
    ON DELETE CASCADE
);