CREATE TABLE internship_status_change
(
    id              bigint generated by default as identity not null,
    author          VARCHAR(255),
    date            TIMESTAMP,
    previous_status VARCHAR(255),
    current_status  VARCHAR(255),
    internship_id   BIGINT,

    CONSTRAINT fk_internship FOREIGN KEY (internship_id)
        REFERENCES internship (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);