drop table if exists internship_week;

drop table if exists internship;

create table internship
(
    id            bigint generated by default as identity not null
        primary key,
    status        varchar(255),
    professor_id  varchar(255)
        constraint should_be_professor_id
            references professor,
    student_index varchar(255)
        constraint should_be_student_index
            references student,
    description   text,
    company_id varchar(255) references company(id)
);

alter table internship
    owner to finki_admin;


create table internship_week
(
    id                  bigint generated by default as identity not null
        primary key,
    description         text,
    end_date            date,
    start_date          date,
    internship_id       bigint
        constraint should_be_internship_id
            references internship,
    company_comment     text,
    coordinator_comment text
);

alter table internship_week
    owner to finki_admin;
